<a href="https://colab.research.google.com/github/jaibairagi01/1dArray/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of NumPy Arrays
1. Allows several Mathematical Operations
2. Faster Operations


In [ ]:
import numpy as np

List vs NumPy - Time Taken

In [ ]:
from time import process_time

Time Taken by a List

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0014915210000001622


In [ ]:
np_array = np.array([i for i in range(10000)])
print(np_array)

start_time = process_time()

np_array += 5
print(np_array)

end_time = process_time()

print(end_time - start_time)

[   0    1    2 ... 9997 9998 9999]
[    5     6     7 ... 10002 10003 10004]
0.001005778000001456


NumPy Arrays


In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating 1D array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape #no. of rows and columns

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8),(9,0,1,2)])
print(b)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]


In [ ]:
b.shape

(3, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initiate Placeholders in Numpy arrays

In [ ]:
# create a numpy arrays of Zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy arrays of ones
y = np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#create for a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.85566701 0.65540701 0.60893411 0.5558733 ]
 [0.59390844 0.40782489 0.08663732 0.39802115]
 [0.852907   0.53967139 0.04834312 0.24678555]]


In [ ]:
#create a random value but contain integers
c = np.random.randint(10,100,(3,4))
print(c)

[[86 14 74 16]
 [48 45 95 58]
 [21 51 35 97]]


In [ ]:
#array of evenly spaced values
d = np.linspace(10,20,5)
print(d)

[10.  12.5 15.  17.5 20. ]


In [ ]:
#arrays of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
#convert a list to a numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
print(type(np_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


Analysing a numpy array


In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[41 71 63 23 14]
 [26 86 34 20 62]
 [10 68 18 61 75]
 [48 28 12 58 31]
 [46 53 52 36 86]]


In [ ]:
#array dimension
print(c.shape)

(5, 5)


In [ ]:
#number of dimensions
print(c.ndim)

2


In [ ]:
#number of elemnts present in array
print(c.size)

25


In [ ]:
#checking the data type of the values in the array
print(c.dtype)

int64


Mathematical Operations on a np array


In [ ]:
list1 = [1,2,3,4,5]
list2 = [5,6,7,8,9]
print((list1 + list2))

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 2 8]
 [2 7 8]
 [0 2 5]]
[[13 12 17]
 [13 19 10]
 [10 18 19]]


In [ ]:
print(a+b)

print(a-b)

print(a*b)

print(b/a)

[[20 14 25]
 [15 26 18]
 [10 20 24]]
[[ -6 -10  -9]
 [-11 -12  -2]
 [-10 -16 -14]]
[[ 91  24 136]
 [ 26 133  80]
 [  0  36  95]]
[[1.85714286 6.         2.125     ]
 [6.5        2.71428571 1.25      ]
 [       inf 9.         3.8       ]]


<ipython-input-55-01a55559fd02>:7: RuntimeWarning: divide by zero encountered in divide
  print(b/a)


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))

[[20 14 25]
 [15 26 18]
 [10 20 24]]
[[ -6 -10  -9]
 [-11 -12  -2]
 [-10 -16 -14]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 3 7]
 [0 1 6]]
(2, 3)


In [ ]:
#tranpose
trans = np.transpose(array)
print(trans)

[[1 0]
 [3 1]
 [7 6]]


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 3 6]
 [0 1 5]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[7 0]
 [3 1]
 [6 5]]
(3, 2)


In [ ]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 6 2]
 [2 7 1]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[6 6]
 [2 2]
 [7 1]]
(3, 2)
